// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzXfl9kQ0RXNZ8MZ6bqd8Sd6Y_RfcRr-Q',
    appId: '1:664434815035:web:e8a526511e8399cda26c1e',
    messagingSenderId: '664434815035',
    projectId: 'injustice-d1650',
    authDomain: 'injustice-d1650.firebaseapp.com',
    storageBucket: 'injustice-d1650.firebasestorage.app',
    measurementId: 'G-H8C8FMQQZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_Er3eOvOUdzQfv6eVwwcs-dftkGPcl00',
    appId: '1:664434815035:android:415aeab4163ebfe5a26c1e',
    messagingSenderId: '664434815035',
    projectId: 'injustice-d1650',
    storageBucket: 'injustice-d1650.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAocv4-zVZtAXz-sWJMHCGLxZTU4CdnlUQ',
    appId: '1:664434815035:ios:ac5f432afb51001aa26c1e',
    messagingSenderId: '664434815035',
    projectId: 'injustice-d1650',
    storageBucket: 'injustice-d1650.firebasestorage.app',
    iosClientId: '664434815035-ljia3a6k5pqsqk3flahtmd3tggelo717.apps.googleusercontent.com',
    iosBundleId: 'com.example.injusticeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAocv4-zVZtAXz-sWJMHCGLxZTU4CdnlUQ',
    appId: '1:664434815035:ios:ac5f432afb51001aa26c1e',
    messagingSenderId: '664434815035',
    projectId: 'injustice-d1650',
    storageBucket: 'injustice-d1650.firebasestorage.app',
    iosClientId: '664434815035-ljia3a6k5pqsqk3flahtmd3tggelo717.apps.googleusercontent.com',
    iosBundleId: 'com.example.injusticeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzXfl9kQ0RXNZ8MZ6bqd8Sd6Y_RfcRr-Q',
    appId: '1:664434815035:web:ee6c762b459fcf30a26c1e',
    messagingSenderId: '664434815035',
    projectId: 'injustice-d1650',
    authDomain: 'injustice-d1650.firebaseapp.com',
    storageBucket: 'injustice-d1650.firebasestorage.app',
    measurementId: 'G-N0ZX3E4EPB',
  );
}
